/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesScrapMaterialRouteImport } from './routes/services.scrap-material'
import { Route as ServicesMaterialSupplyRouteImport } from './routes/services.material-supply'
import { Route as ServicesManpowerSupplyRouteImport } from './routes/services.manpower-supply'
import { Route as ServicesFencingWorksRouteImport } from './routes/services.fencing-works'
import { Route as ServicesEquipmentRentalRouteImport } from './routes/services.equipment-rental'
import { Route as ServicesDisposalProductRouteImport } from './routes/services.disposal-product'
import { Route as ServicesCivilConstructionRouteImport } from './routes/services.civil-construction'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesScrapMaterialRoute = ServicesScrapMaterialRouteImport.update({
  id: '/services/scrap-material',
  path: '/services/scrap-material',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaterialSupplyRoute = ServicesMaterialSupplyRouteImport.update({
  id: '/services/material-supply',
  path: '/services/material-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesManpowerSupplyRoute = ServicesManpowerSupplyRouteImport.update({
  id: '/services/manpower-supply',
  path: '/services/manpower-supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFencingWorksRoute = ServicesFencingWorksRouteImport.update({
  id: '/services/fencing-works',
  path: '/services/fencing-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEquipmentRentalRoute = ServicesEquipmentRentalRouteImport.update({
  id: '/services/equipment-rental',
  path: '/services/equipment-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDisposalProductRoute = ServicesDisposalProductRouteImport.update({
  id: '/services/disposal-product',
  path: '/services/disposal-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCivilConstructionRoute =
  ServicesCivilConstructionRouteImport.update({
    id: '/services/civil-construction',
    path: '/services/civil-construction',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/services/civil-construction': typeof ServicesCivilConstructionRoute
  '/services/disposal-product': typeof ServicesDisposalProductRoute
  '/services/equipment-rental': typeof ServicesEquipmentRentalRoute
  '/services/fencing-works': typeof ServicesFencingWorksRoute
  '/services/manpower-supply': typeof ServicesManpowerSupplyRoute
  '/services/material-supply': typeof ServicesMaterialSupplyRoute
  '/services/scrap-material': typeof ServicesScrapMaterialRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/services/civil-construction': typeof ServicesCivilConstructionRoute
  '/services/disposal-product': typeof ServicesDisposalProductRoute
  '/services/equipment-rental': typeof ServicesEquipmentRentalRoute
  '/services/fencing-works': typeof ServicesFencingWorksRoute
  '/services/manpower-supply': typeof ServicesManpowerSupplyRoute
  '/services/material-supply': typeof ServicesMaterialSupplyRoute
  '/services/scrap-material': typeof ServicesScrapMaterialRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/services/civil-construction': typeof ServicesCivilConstructionRoute
  '/services/disposal-product': typeof ServicesDisposalProductRoute
  '/services/equipment-rental': typeof ServicesEquipmentRentalRoute
  '/services/fencing-works': typeof ServicesFencingWorksRoute
  '/services/manpower-supply': typeof ServicesManpowerSupplyRoute
  '/services/material-supply': typeof ServicesMaterialSupplyRoute
  '/services/scrap-material': typeof ServicesScrapMaterialRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/company-profile'
    | '/contact'
    | '/services/civil-construction'
    | '/services/disposal-product'
    | '/services/equipment-rental'
    | '/services/fencing-works'
    | '/services/manpower-supply'
    | '/services/material-supply'
    | '/services/scrap-material'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/company-profile'
    | '/contact'
    | '/services/civil-construction'
    | '/services/disposal-product'
    | '/services/equipment-rental'
    | '/services/fencing-works'
    | '/services/manpower-supply'
    | '/services/material-supply'
    | '/services/scrap-material'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/company-profile'
    | '/contact'
    | '/services/civil-construction'
    | '/services/disposal-product'
    | '/services/equipment-rental'
    | '/services/fencing-works'
    | '/services/manpower-supply'
    | '/services/material-supply'
    | '/services/scrap-material'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ContactRoute: typeof ContactRoute
  ServicesCivilConstructionRoute: typeof ServicesCivilConstructionRoute
  ServicesDisposalProductRoute: typeof ServicesDisposalProductRoute
  ServicesEquipmentRentalRoute: typeof ServicesEquipmentRentalRoute
  ServicesFencingWorksRoute: typeof ServicesFencingWorksRoute
  ServicesManpowerSupplyRoute: typeof ServicesManpowerSupplyRoute
  ServicesMaterialSupplyRoute: typeof ServicesMaterialSupplyRoute
  ServicesScrapMaterialRoute: typeof ServicesScrapMaterialRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/scrap-material': {
      id: '/services/scrap-material'
      path: '/services/scrap-material'
      fullPath: '/services/scrap-material'
      preLoaderRoute: typeof ServicesScrapMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/material-supply': {
      id: '/services/material-supply'
      path: '/services/material-supply'
      fullPath: '/services/material-supply'
      preLoaderRoute: typeof ServicesMaterialSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/manpower-supply': {
      id: '/services/manpower-supply'
      path: '/services/manpower-supply'
      fullPath: '/services/manpower-supply'
      preLoaderRoute: typeof ServicesManpowerSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/fencing-works': {
      id: '/services/fencing-works'
      path: '/services/fencing-works'
      fullPath: '/services/fencing-works'
      preLoaderRoute: typeof ServicesFencingWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/equipment-rental': {
      id: '/services/equipment-rental'
      path: '/services/equipment-rental'
      fullPath: '/services/equipment-rental'
      preLoaderRoute: typeof ServicesEquipmentRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/disposal-product': {
      id: '/services/disposal-product'
      path: '/services/disposal-product'
      fullPath: '/services/disposal-product'
      preLoaderRoute: typeof ServicesDisposalProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/civil-construction': {
      id: '/services/civil-construction'
      path: '/services/civil-construction'
      fullPath: '/services/civil-construction'
      preLoaderRoute: typeof ServicesCivilConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ContactRoute: ContactRoute,
  ServicesCivilConstructionRoute: ServicesCivilConstructionRoute,
  ServicesDisposalProductRoute: ServicesDisposalProductRoute,
  ServicesEquipmentRentalRoute: ServicesEquipmentRentalRoute,
  ServicesFencingWorksRoute: ServicesFencingWorksRoute,
  ServicesManpowerSupplyRoute: ServicesManpowerSupplyRoute,
  ServicesMaterialSupplyRoute: ServicesMaterialSupplyRoute,
  ServicesScrapMaterialRoute: ServicesScrapMaterialRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
